/**
 * Config pública para o browser. Cada `process.env.NEXT_PUBLIC_*` precisa ser
 * escrito por extenso — é assim que o Next inlina o valor no bundle.
 */
import { parsePublicConfig } from '@/lib/config'

export const publicConfig = parsePublicConfig({
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_TRACKING_MODE: process.env.NEXT_PUBLIC_TRACKING_MODE,
  NEXT_PUBLIC_GTM_ID: process.env.NEXT_PUBLIC_GTM_ID,
  NEXT_PUBLIC_META_PIXEL_ID: process.env.NEXT_PUBLIC_META_PIXEL_ID,
  NEXT_PUBLIC_GA4_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA4_MEASUREMENT_ID,
  NEXT_PUBLIC_GA4_LEAD_SOURCE: process.env.NEXT_PUBLIC_GA4_LEAD_SOURCE,
  NEXT_PUBLIC_GOOGLE_ADS_ID: process.env.NEXT_PUBLIC_GOOGLE_ADS_ID,
  NEXT_PUBLIC_GOOGLE_ADS_LEAD_LABEL: process.env.NEXT_PUBLIC_GOOGLE_ADS_LEAD_LABEL,
  NEXT_PUBLIC_GOOGLE_ADS_RESERVATION_LABEL: process.env.NEXT_PUBLIC_GOOGLE_ADS_RESERVATION_LABEL,
  NEXT_PUBLIC_GOOGLE_ADS_CONTACT_LABEL: process.env.NEXT_PUBLIC_GOOGLE_ADS_CONTACT_LABEL,
  NEXT_PUBLIC_LINKER_DOMAINS: process.env.NEXT_PUBLIC_LINKER_DOMAINS,
  NEXT_PUBLIC_CLARITY_ID: process.env.NEXT_PUBLIC_CLARITY_ID,
  NEXT_PUBLIC_CONSENT_MODE: process.env.NEXT_PUBLIC_CONSENT_MODE,
  NEXT_PUBLIC_SERVER_PAGEVIEW: process.env.NEXT_PUBLIC_SERVER_PAGEVIEW,
})
